<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_Hitung</name>
   <tag></tag>
   <elementGuidId>0e628891-bed7-4a66-96be-8c6617fd8f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hitung_harga_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hitung_harga_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#hitung_harga_button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ca7dd46-5a10-4654-a8b1-afeb8b5956a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hitung_harga_button</value>
      <webElementGuid>301aac2f-109c-4db6-ac6b-e17a5e01ac16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 col-md-6 p-0</value>
      <webElementGuid>26ad62a0-825e-4958-ad8c-7107884dd86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hitung Ulang</value>
      <webElementGuid>92b1765f-5b0e-456d-9022-28eac0d187e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hitung_harga_button&quot;)</value>
      <webElementGuid>f2998d0c-0c61-495f-bdb7-fa9e2191b573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='hitung_harga_button']</value>
      <webElementGuid>d4ed8cb0-e34b-4fa7-8fdb-289a8d457747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_hitung_harga']/div[2]</value>
      <webElementGuid>da57c04c-63cb-4349-8835-b51ab1d06144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu'])[2]/following::div[1]</value>
      <webElementGuid>dbad5b51-4696-4367-8fc0-1d9601330e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per Bulan'])[2]/following::div[2]</value>
      <webElementGuid>ed179473-fa45-46eb-94d7-2f1e474f68fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Properti Maksimal Kamu'])[1]/preceding::div[1]</value>
      <webElementGuid>99d69df6-514f-4281-893d-c211b834b59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]</value>
      <webElementGuid>871589a0-e449-4937-bfc9-6d172d4724bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hitung_harga_button' and (text() = 'Hitung Ulang' or . = 'Hitung Ulang')]</value>
      <webElementGuid>73fd4312-78e4-47f3-b66d-8a02144d470d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
