<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hitung Harga Properti Maksimal_floati_bf0ef7</name>
   <tag></tag>
   <elementGuidId>8d1245f9-a5c5-46d6-aa73-336450ce3ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.floating-label-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Penghasilan Total&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b868d688-0a75-4d35-8376-0d9cdfbf0093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>177b6c90-c1e8-4ea7-9907-536a5376627a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-label-field</value>
      <webElementGuid>7586f8eb-f4c9-4817-abcf-3d604e699ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Penghasilan Total</value>
      <webElementGuid>7068a94a-8400-4772-8f21-0e6d507da0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c136ae83-6748-4997-a19d-b68c97c2655f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_hitung_harga&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;floating-label-wrap&quot;]/input[@class=&quot;floating-label-field&quot;]</value>
      <webElementGuid>c7021422-51f3-4029-b626-b7ebadc63c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>2caf245a-cafa-4fed-9f27-7bfd55a2a2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_hitung_harga']/div/div/input</value>
      <webElementGuid>fb49fb32-b0bb-4684-b77d-dd81775b4e82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>0400359d-75d5-45ea-b98b-b2cf351e1fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Penghasilan Total']</value>
      <webElementGuid>34eefc8c-d861-4957-9d86-c0745a067863</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
