<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kotakhasil</name>
   <tag></tag>
   <elementGuidId>80cc2512-1105-42d8-b446-3efecc40383b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#harga_hasil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='harga_hasil']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Harga Properti Maksimal KamuRp 8.000.000Langsung cari di area yang kamu inginkan&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7aec8d7c-5fe3-441c-abd6-9837a99253e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>harga_hasil</value>
      <webElementGuid>bf2e9a49-f3b0-404d-ac88-236e5af9b476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-center flex-column</value>
      <webElementGuid>cec2d44b-1f09-4c8f-80c3-20cc12ceedbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harga Properti Maksimal KamuRp 8.000.000Langsung cari di area yang kamu inginkanLokasi</value>
      <webElementGuid>2843dd49-0ebc-4723-a8f5-e44ed071aa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga_hasil&quot;)</value>
      <webElementGuid>24831e80-22fe-4fa7-a8e2-0f004ed9ab70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='harga_hasil']</value>
      <webElementGuid>4bf87a7e-6cd0-4de0-b41b-978eb01aaf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hitung_harga']/div/div/div/div[2]/div/div/div[3]/div</value>
      <webElementGuid>cb444f3a-e5d7-4b74-8e0d-6f819f3822e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitung Ulang'])[1]/following::div[2]</value>
      <webElementGuid>ffcbb6a1-16d7-4e85-8e59-85a3b4a06721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jangka Waktu'])[2]/following::div[3]</value>
      <webElementGuid>c783bfe1-aa8a-419f-b04b-8cc33fed9470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div</value>
      <webElementGuid>4ea218e0-09e6-45f4-ae40-1e64c853ec46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'harga_hasil' and (text() = 'Harga Properti Maksimal KamuRp 8.000.000Langsung cari di area yang kamu inginkanLokasi' or . = 'Harga Properti Maksimal KamuRp 8.000.000Langsung cari di area yang kamu inginkanLokasi')]</value>
      <webElementGuid>e6639e6b-e0ce-47d8-a245-f6aa0233059b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
